#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo "Setting up your Mac..."

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh


echo 'Install composer'
echo '----------------'
cd ~/.dotfiles
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"


if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    echo 'ERROR: Invalid Composer installer signature'
    rm composer-setup.php
else
    php composer-setup.php --quiet
    rm composer-setup.php
    echo 'move composer to /usr/local/bin/composer'
    sudo mv -f composer.phar /usr/local/bin/composer
fi


echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Update Homebrew recipes
brew update


# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

echo 'Install node'
echo '-----------'
brew install node@10

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package


echo 'Install php'
echo '-----------'
brew install php@7.1
brew install php@7.3

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/installer laravel/valet
valet install
mkdir $HOME/Sites

echo 'Install mysql'
echo '-------------'
brew install mysql@5.7
brew services start mysql@5.7

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install chrome'
echo '---------------------------'
brew cask install google-chrome

echo 'Install iterm2'
echo '---------------------------'
brew cask install iterm2

echo 'Install phpstorm'
echo '---------------------------'
brew cask install phpstorm

echo 'Install sublime-text'
echo '---------------------------'
brew cask install sublime-text

echo 'Install firefox'
echo '---------------------------'
brew cask install firefox


echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
